#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-builder.yml
# Description: Build OpenWrt multi-profile for all devices using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
# Copyright (c) 2025 icyray
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build Multi-Profile Immortalwrt 24.10-6.6

on:
  repository_dispatch:
  workflow_dispatch:

env:
  UPDATER_ENABLED: true
  UPDATER_DEFCONFIG: mtk_filogic.config

jobs:
  build:
    uses: ./.github/workflows/image-builder.yml
    with:
      repo_url: https://github.com/padavanonly/immortalwrt-mt798x-24.10
      repo_branch: openwrt-24.10-6.6
      config_file: mtk_filogic.config
      diy_p1_sh: diy-part1.sh
      diy_p2_sh: mtk_filogic.sh
      feeds_conf: feeds.conf.default
      release_file: release.md
      upload_bin_dir: false
      upload_firmware: true
      upload_release: true
      tz: Asia/Shanghai
